### ISSUE TITLE
Fresh Install error

### ISSUE THREAD

**Issue by seigneur** [lamassu/lamassu-install#13]
Error is associated with "ssu-raqia": "./bin/ssu-raqia"  whilst installing lamassu-scripts the file is no longer there.

94 verbose stack Error: ENOENT, chmod '/usr/local/lib/node_modules/lamassu-scripts/bin/ssu-raqia'
95 verbose cwd /usr/local/lib/node_modules/lamassu-scripts
96 error Linux 3.13.0-52-generic
97 error argv "node" "/usr/local/bin/npm" "install"
98 error node v0.10.32
99 error npm  v2.12.1
100 error path /usr/local/lib/node_modules/lamassu-scripts/bin/ssu-raqia
101 error code ENOENT
102 error errno 34
103 error enoent ENOENT, chmod '/usr/local/lib/node_modules/lamassu-scripts/bin/ssu-raqia'
103 error enoent This is most likely not a problem with npm itself
103 error enoent and is related to npm not being able to find a file.
104 verbose exit [ 34, true ]

**Comment by naconner** [comment]
Thanks @seigneur. That's a known issue due to an error in lamassu-scripts@latest. Should be fixed soon. In the meantime, you may use lamassu-scripts@0.2.10 safely for now.

You can edit to this in lamassu-install@master:

```
npm -g install lamassu-server lamassu-admin lamassu-scripts@0.2.10 migrate >> $debug 2>&1
```

Or on lamassu-install@two-way:

```
npm -g install lamassu-server@two-way lamassu-admin lamassu-scripts@0.2.10 migrate bunyan >> $debug 2>&1
```

**Comment by seigneur** [comment]
Thanks
