### ISSUE TITLE
Operator-created script for Debian install

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-install#3]
https://github.com/runderwo/lamassu-debian

Awaiting confirmation of successful pairing.

**Comment by runderwo** [comment]
I should assume you're no longer interested in this?

**Comment by naconner** [comment]
@runderwo We're preparing for a new install script:

**Comment by naconner** [comment]
@runderwo We're preparing for a new install script and server branch:

https://github.com/lamassu/lamassu-install/tree/alpha

Will have configuration instructions for the public alpha in the coming weeks. Feel free to adapt for Debian and submit a pull request.
